GitHub Actions: Try to fix SSL exception while downloading fred dependencies by upgrading to latest Ubuntu version
Gradle would fail on Java 9 and 10 (but succeed on 8 to 16 otherwise)
with:
> Could not GET 'https://mvn.freenetproject.org/org/freenetproject/freenet-ext/29/freenet-ext-29.pom'.
> sun.security.validator.ValidatorException: PKIX path building failed:
> sun.security.provider.certpath.SunCertPathBuilderException: unable to
> find valid certification path to requested target

I suspect the old one lacks the most recent SSL certificates necessary
to build a trust path.