Class Freetalk: Fix NoClassDefFoundError on Java 9
Would fail on Travis CI as:
	$ java -Xmx32m -version
	Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
	java version "9.0.1"
	Java(TM) SE Runtime Environment (build 9.0.1+11)
	Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
	[...]
	[junit] Running plugins.Freetalk.DatabaseBasedTest
	[junit] Testsuite: plugins.Freetalk.DatabaseBasedTest
	[junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.397 sec
	[junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.397 sec
	[junit]
	[junit] Testcase: testSelf took 0.388 sec
	[junit] 	Caused an ERROR
	[junit] javax/activation/MimeTypeParseException
	[junit] java.lang.NoClassDefFoundError: javax/activation/MimeTypeParseException
	[junit] 	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	[junit] 	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3024)
	[junit] 	at java.base/java.lang.Class.getDeclaredFields(Class.java:2205)
	[junit] 	at plugins.Freetalk.Freetalk.getNewDatabaseConfiguration(Freetalk.java:376)
	[junit] 	at plugins.Freetalk.Freetalk.openDatabase(Freetalk.java:416)
	[junit] 	at plugins.Freetalk.Freetalk.<init>(Freetalk.java:168)
	[junit] 	at plugins.Freetalk.DatabaseBasedTest.setUp(DatabaseBasedTest.java:51)
	[junit] Caused by: java.lang.ClassNotFoundException: javax.activation.MimeTypeParseException
	[junit] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	[junit] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	[junit] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)

Source: https://travis-ci.org/xor-freenet/plugin-Freetalk/jobs/426241449

Reason is explained at JavaDoc of class plugins.Freetalk.util.MimeType.